Hds/breadcrumb update
HighOutputVentures/hds pull request #214
Opened 2023-01-24 08:26 UTC by jade-kenneth

2023-01-24 08:28 UTC, lcjay2212 approved these changes

2023-01-24 16:01 UTC, nberongoy approved these changes

2023-01-24 16:02 UTC, nberongoy requested changes

2023-01-24 16:02 UTC, nberongoy commented on packages/breadcrumbs/src/Breadcrumbs.tsx
>                      ? '#EDE8FC'
dont use hex value use the color system

2023-01-25 01:45 UTC, nberongoy approved these changes

2023-01-25 02:18 UTC, merged